# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  setup:
    name: Update Assets
    # Set machine up, clone repo
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: actions-marketplace-validations/curoky_cleanup-disk-action@master
        with:
          retain: "python,node"

      - name: Install hub
        run: |
          sudo apt-get update
          sudo apt-get install -y hub
          
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 15
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" #install the python needed
    
      # Optimize images
      - name: Optimize images
        run: |
          sudo apt install -y optipng
          python scripts/optimize.py
          git config --global user.name 'Buildbot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Optimize images"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # Calculate average sizes
      - name: Calculate average sizes
        run: |
          pip install pillow
          python scripts/calc_avg.py
          git config --global user.name 'Buildbot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Add averages"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # Generate StartGG config insights
      - name: Generate StartGG config insights
        run: |
          pip install requests
          python scripts/check_startgg_config.py
          git config --global user.name 'Buildbot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update startgg config insights"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # Update version numbers
      - name: Update version numbers
        run: |
          python scripts/update_calver.py
          git config --global user.name 'Buildbot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          git add .
          if ! git diff --cached --quiet; then
            git commit -m "Update version number of changed packs"
            git push origin main
          else
            echo "No changes to commit"
          fi

      # Run assets build logic
      - name: execute py script
        run: |
          python gen_config.py
      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global http.lowSpeedLimit 0      # Disable low speed limit
          git config --global http.lowSpeedTime 999999  # Set a very large low speed time to effectively disable the timeout

          # Commit
          git config --global user.name 'Buildbot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          find . -name "*~" -type f -delete
          git add assets.json last_versions.json scripts/last_tag.txt
          git commit -m "Update assets"
          git push origin main

          set -x
          assets=()
          for asset in $(find . -name "*.7z*"); do
            assets+=("-a" "${asset}")
          done
          hub release create "${assets[@]}" -m "${GITHUB_SHA::8}" "${GITHUB_SHA::8}"

      # DO NOT ADD ANYTHING AFTER THIS LINE (Files are deleted from the agent to free space and we should avoid committing the deletion)
