# This is a basic workflow to help you get started with Actions

name: Build Release

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  #pull_request:
  #  branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: Upload Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Free Disk Space (Ubuntu)
        uses: curoky/cleanup-disk-action@v2.0
        with:
          retain: 'python,node'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9" #install the python needed
      - name: execute py script # run the run.py to get the latest data
        run: |
          python gen_config.py
      - name: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name 'Buildbot'
          git config --global user.email 'buildbot@users.noreply.github.com'
          git add .
          git commit -m "Update assets"
          git push origin main
          set -x
          assets=()
          for asset in $(find . -name "*.7z*"); do
            assets+=("-a" "${asset}")
          done
          hub release create "${assets[@]}" -m "${GITHUB_SHA::8}" "${GITHUB_SHA::8}"
